namespace Quizzik_Project.DTO
{
    public class QuizDTO
    {
        public int QuizID { get; set; } // This will be generated by the database
        public string? Title { get; set; }
        public string? Description { get; set; }
        public int UserID { get; set; }
        public DateTime CreatedAt { get; set; } = DateTime.Now;
    }
}
